### ISSUE TITLE
ビザンチン将軍問題のｆとｔ

### ISSUE THREAD

**Issue by yokota101010** [blockchain-programming/book2021#26]
ビザンチン将軍問題の節の中に「嘘つきノード数をｆとしたとき、３ｔ≧ｎの場合には・・・」という文がありますが、ｆとｔは同じものを表すでしょうか。

**Comment by ShigeichiroYamasaki** [comment]
山崎です

この場合の t と f は同じものです．
私の手元の「ブロックチェーン技術概論」の書籍（第１刷）の21ページでは，  「3f ≧ n の場合には・・・」となっています．
印刷の問題かもしれません．

**Comment by yokota101010** [comment]
了解しました。ありがとうございました。
