### ISSUE TITLE
利得の和の最大化とパレート最適の関係について

### ISSUE THREAD

**Issue by yokota101010** [blockchain-programming/book2021#27]
「パレート最適性」の節にて、最後の方に「これよりも大きな利得の和をもつ戦略の組み合わせは存在しないので、この2つの組み合わせがパレート最適になります」とありますが、前半では「全プレイヤーの利得の和で集団合理性を評価する方法は、1つのわかりやすい方法ではありますが、これが集団合理性の定義ではありません」とあります。

また「リヴァイアサン型トラストによるパレート最適の実現」の節でも「人々の利得の和を最大化するパレート最適を実現可能にします」とあります。

”パレート最適”と”利得の和の最大化”は異なる概念だと思うのですが、どのように考えたら良いでしょうか？

**Comment by ShigeichiroYamasaki** [comment]
山崎です

ご指摘ありがとうございます
確かにご指摘のとおりです．”パレート最適”と”利得の和の最大化”は異なる概念です．

「人々の利得の和を最大化するパレート最適を実現可能にします」
を以下のように修正したいと思います．
「人々の利得を最大化する戦略の組み合わせであるパレート最適を実現可能にします」

**Comment by yokota101010** [comment]
回答ありがとうございました。了解いたしました。
