### ISSUE TITLE
「ブロックチェーンがそもそもフォークしないなら、プルーフ・オブ・ワークの計算も不要になります。」とは？

### ISSUE THREAD

**Issue by yokota101010** [blockchain-programming/book2021#28]
「PBFT」の節にて「ブロックチェーンがそもそもフォークしないなら、プルーフ・オブ・ワークの計算も不要になります。」とありますが、これはどういう意味で不要なのでしょうか？
たとえフォークしなくても改ざん出来ないようにするためにはプルーフ・オブ・ワークの計算は必要なのではないかと思いました。

**Comment by ShigeichiroYamasaki** [comment]
山崎です

ご指摘ご質問ありがとうございます．

ご指摘のように，ここの説明は正確性を欠いておりました．

書籍では，「ブロックチェーンの分岐（フォーク）」という文脈で説明していますが，ここでの議論の本質は分散台帳のコンセンサス（合意）です．
「ビザンチン将軍問題」のトピックで結託して合意を妨げようとするノードが 1/3 を超える場合には「合意アルゴリズムが存在しない」という定理の存在を挙げていますが， アルゴリズムが無いことと合意ができないことは同じではありません．

サトシナカモトのProof of Work法 はアルゴリズムでなくゲーム理論的な方法で合意を妨げるようとするノードが 1/2 未満ならば合意状態に収束させる方法です．

本書で 「PBFT」の節にて「ブロックチェーンがそもそもフォークしないなら、プルーフ・オブ・ワークの計算も不要になります。」 と書いていることの本位は，「もし信頼できるノードが 2/3 以上存在し，合意アルゴリズムが存在することを前提にするならば，PBFTのような合意アルゴリズム使って分散台帳のコンセンサスを形成できる」と言いたかったのです．

ご指摘の改ざんについてですが，PBFTの前提は， 2/3 以上の信頼できるノードの存在が前提になっていますから， 1/3 未満ががんばっても改ざんは不可能ということになります．

Proof ofWork法でも，1/2以上のノードが結託すれば改ざんは可能です（51%攻撃）．
実際に bitcoin gold というブロックチェーンでは２回もそういう事件が発生しています．

**Comment by yokota101010** [comment]
ご説明ありがとうございました。理解しました。
