### ISSUE TITLE
（付録）剰余群Z/nZの演算子として乗法を定義できるか

### ISSUE THREAD

**Issue by yokota101010** [blockchain-programming/book2021#30]
Z/2Z＝｛0、1｝の群としての性質を考えると、まず単位元は’1’になると思います。次に’0’の逆元を考えると、’0’に何を掛けても’0’なので逆元は存在しません。従って、Z/2Zは群ではないと思われるのですが、いかがでしょうか？

**Comment by ShigeichiroYamasaki** [comment]
山崎です 

Z/2Z＝｛0、1｝ は加法について群になります
また，乗法については，0 を除いた 1点集合として群になります．
一般的に乗法群について考えるときには，集合から {0} を除くという注意を付加しますが，
その理由は，そもそも 0 は乗法 × という演算の対象ではないからです．

自然数 1,2,3, …

に対して 0 の発見は人類の数学の歴史にとって大発見でした．
 0 の用法は，常にその定義へのパラフレーズが必要です．
0の使い方には位取りなどの用法もありますが，
代数構造においての 0 という「数」は加法単位元として定義された「数」の記号（名前）です．

A × 0 = 0 という等式は，体や環の演算（加法と乗法の両方を持つ代数構造）の中で導入されます
(A + (-A))×0 = A×0 + (-A)×0

したがって Z/2Z や 一般に  Z/nZ は乗法についても群になります．

**Comment by ShigeichiroYamasaki** [comment]
山崎です

メールに誤りがありました．

> したがって Z/2Z や 一般に  Z/nZ は乗法についても群になります．

Z/nZ は一般には群にはなりません． nが素数のときだけ群になります．

ついでに説明を追加すると， 0が乗法× の対象ではないことは，逆元操作である 0での割り算や0を分母にする分数が定義されないのと同様です．

**Comment by yokota101010** [comment]
> 一般的に乗法群について考えるときには，集合から {0} を除くという注意を付加しますが，

については認識していませんでした。ありがとうございました。
