### ISSUE TITLE
（付録）拡張ユークリッド互除法

### ISSUE THREAD

**Issue by yokota101010** [blockchain-programming/book2021#31]
ベズー方程式（ａｘ＋ｂｙ＝ｄ）の整数解を求める方法として紹介されている拡張ユークリッド互除法ですが、その計算例である表　付録．１にも表　付録．２にもｄが使われていないです。表の前の解説部分でもｄが唐突に消えており、論理が接続していないように思われます。

**Comment by ShigeichiroYamasaki** [comment]
山崎です

ご指摘ありがとうございます．
ここの d は gcd のことであるという記述を書くべきでした．

P. 325 の第４パラグラフ 「例として 〜」の最後に次の一文を追加したいと思います．

ベズー方程式のd は最大公約数なので，下表では， d を gcd と表示します．

**Comment by yokota101010** [comment]
了解しました。
